# Generated by Django 4.2.5 on 2023-10-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('key', models.CharField(max_length=36, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('user_name', models.CharField(max_length=32, null=True)),
                ('photo', models.CharField(max_length=120, null=True)),
                ('registration_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
