# Generated by Django 4.2.5 on 2023-10-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('user_name', models.CharField(max_length=32, null=True)),
                ('registration_date', models.DateField(auto_now_add=True, null=True)),
                ('description', models.CharField(max_length=512, null=True))
            ],
        ),
    ]
